---
driver:
  name: docker
  image: centos:6.7
  use_sudo: <%= ENV['DOCKER_SUDO'] %>

provisioner:
  name: puppet_apply
  modules_path: modules
  manifests_path: manifests
  puppet_verbose: true
  puppet_debug: true

platforms:
  - name: centos

suites:
  - name: default
    manifest: site.pp
